name: Code Coverage
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      # To generate the coverage report
      # Add 'json-summary' to coverageReporters in jest options
      - name: Tests
        run: yarn test-ci
      - name: Generate coverage badges
        uses: jpb06/jest-badges-action@latest
          with:
            branches: main, dev, staging
